FROM openjdk:8
VOLUME /tmp
EXPOSE 8080
COPY build/libs/ssen-project-1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul
RUN apt-get install -y tzdata