FROM openjdk:8
VOLUME /tmp
EXPOSE 8081
ARG JAR_FILE=build/libs/ssen-news-project-1.0-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
COPY ./J7E204T.pem /home/ubuntu/J7E204T.pem
ENTRYPOINT ["java","-jar","/app.jar"]
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul
RUN apt-get install -y tzdata